image: docker:dind
    
cache:
  untracked: true
  key: "$CI_BUILD_REF_NAME"
  paths:
    - node_modules/
    
variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375
  KUBECONFIG: "/etc/deploy/config"
  IMAGE: registry.gitlab.com/lee-websites/frontend/home
stages:
    - setup
    - test
    - build
    - deploy
setup:
    stage: setup
    image: node:12.0.0-alpine
    script:
        - npm install
    artifacts:
        paths:
            - node_modules/
test:
    stage: test
    image: node:12.0.0-alpine
    script:
        - npm run lint
build_site:
    stage: build
    script:
      - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
      - docker build -t ${IMAGE} . -f Dockerfile
      - docker tag ${IMAGE} ${IMAGE}:${CI_COMMIT_SHORT_SHA}
      - docker tag ${IMAGE} ${IMAGE}:latest
      - docker push ${IMAGE}
.k8s-deploy: &k8s-deploy
  image: dtzar/helm-kubectl
  before_script:
    - mkdir -p /etc/deploy
    - echo ${KUBE_CONFIG} | base64 -d > ${KUBECONFIG}
  script:
    - kubectl config use-context $KUBECONTEXT
    - helm init --client-only
    - helm upgrade kappes-space-home ./ --install --namespace kappes-space --set image.tag=${CI_COMMIT_SHORT_SHA}
deploy_production_site:
    stage: deploy
    variables:
      KUBECONTEXT: "kappes-space"
    <<: *k8s-deploy
    environment:
      name: production
    only:
    - master