image: docker:dind

services:
    - docker:dind
    
cache:
  untracked: true
  key: "$CI_BUILD_REF_NAME"
  paths:
    - node_modules/

    
variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://localhost:2375
    
    IMAGE: registry.gitlab.com/lee-websites/frontend/home

stages:
    - setup
    - test
    - build
    - deploy

setup:
    stage: setup
    image: node
    script:
        - npm install
    artifacts:
        paths:
            - node_modules/

test:
    stage: test
    image: node
    script:
        - npm run lint

build_site:
    stage: build
    script:
      - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
      - docker build -t ${IMAGE} . -f Dockerfile
      - docker tag ${IMAGE} ${IMAGE}:${CI_COMMIT_SHORT_SHA}
      - docker tag ${IMAGE} ${IMAGE}:latest
      - docker push ${IMAGE}
      
deploy_staging_site:
    stage: deploy
    image: dtzar/helm-kubectl
    script:
      - kubectl config set-cluster k8s --server="${KUBE_URL}"
      - kubectl config set clusters.k8s.certificate-authority ${KUBE_CA_PEM_FILE}
      - kubectl config set-credentials gitlab --token="${KUBE_TOKEN}"
      - kubectl config set-context default --cluster=k8s --user=gitlab
      - kubectl config use-context default
      - kubectl apply -f k8s/kubernetes.yml
    environment:
      name: staging
    only:
    - master



