apiVersion: apps/v1
kind: Deployment
metadata:
  name: site
  namespace: leon-kappes-space
spec:
  replicas: 4
  selector:
    matchLabels:
      app: site
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  template:
    spec:
      containers:
      - name: site
        image: registry.gitlab.com/lee-websites/frontend/home
        imagePullPolicy: always
        ports:
          - containerPort: 5000
      imagePullSecrets:
      - name: gitlab-auth

---
apiVersion: v1
kind: Service
metadata:
  name: site
  namespace: leon-kappes-space
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: site
  type: LoadBalancer
  
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  name: site
spec:
  rules:
  - host: kappes.space
    http:
      paths:
      - path: /
        backend:
          serviceName: site
          servicePort: 80
