apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: home-site-deployment
  namespace: leon-kappes-space
spec:
  replicas: 4
  selector:
    matchLabels:
      app: home-site
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: home-site
    spec:
      containers:
      - name: home-site
        image: registry.gitlab.com/lee-websites/frontend/home
        imagePullPolicy: always
        ports:
          - containerPort: 5000
      imagePullSecrets:
      - name: gitlab-auth
---
apiVersion: v1
kind: Service
metadata:
  name: home-site-service
  namespace: leon-kappes-space
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: home-site
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: home-site-ingress
  namespace: leon-kappes-space
  annotations:
   kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - host: kappes.space
    http:
      paths:
      - path: /
        backend:
          serviceName: home-site-service
          servicePort: 80