apiVersion: apps/v1
kind: Deployment
metadata:
  name: kappes-space-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: kappes-space
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: kappes-space
    spec:
      containers:
      - name: site
        image: registry.gitlab.com/lee-websites/frontend/home:{{ .Values.image.tag }}
        imagePullPolicy: Always
        ports:
          - containerPort: 5000
      imagePullSecrets:
      - name: gitlab-auth

