apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  name: kappes-space-ingress
spec:
  rules:
  - host: kappes.space
    http:
      paths:
      - path: /
        backend:
          serviceName: kappes-space-service
          servicePort: 80
