name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has been marked as stale because there was no activity in the last 15 days!'
        stale-pr-message: 'This pull request has been marked as stale because there was no activity in the last 15 days!'
        stale-issue-label: 'stale'
        stale-pr-label: 'stale'
        days-before-stale: 15
        days-before-close: 3
